# Generated by Django 6.0.2 on 2026-02-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='avoidance_strategy',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='detailed_strategy',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='final_verdict',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='similar_patent',
            field=models.CharField(default='해당 없음', max_length=255),
        ),
    ]
